spring:
  config:
    activate:
      on-profile: prod

name: prod-YAML
environment: production
enabled: true
servers:
  - www.abc.com
  - www.xyz.com
server:
  port: 9090
---

spring:
  config:
    activate:
      on-profile: dev

name: dev-YAML
environment: development
enabled: false
servers:
  - www.abc.com
  - www.xyz.com
server:
  port: 8080